### ISSUE TITLE
auro-accordion: z-index cannot transcend the shadow-root

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-accordion#39]
## Describe the bug
When putting our planbook component in the auro-accordion content slot, the z-index is not respected and the content which should pop out instead scrolls the entire slot down.

## Screenshots
Expected:
![image](https://user-images.githubusercontent.com/7005799/141530708-37fe4310-f83b-4429-a05b-d7b835be31d5.png)
This was generated with:
```
      <auro-accordion noProfile="true" chromeless="true" justifyLeft>
        <span class="accordion-text" slot="trigger">Change your search</span>

      </auro-accordion>
      <div class="planbook">
        <Planbook on:planbookSubmit={(evt) => handleMessage(evt)}></Planbook>
      </div>
```

Actual:

![image](https://user-images.githubusercontent.com/7005799/141530614-15f56d19-3db9-4701-8e16-0900136a104b.png)
This was generated with:
```
      <auro-accordion noProfile="true" chromeless="true" justifyLeft>
        <span class="accordion-text" slot="trigger">Change your search</span>
      <div class="planbook">
        <Planbook on:planbookSubmit={(evt) => handleMessage(evt)}></Planbook>
      </div>
      </auro-accordion>

```

**Comment by blackfalcon** [comment]
Can you include a test URL and a video of the issue? These issues are really difficult to troubleshoot via a screenshot.

**Comment by gusnaughton** [comment]
Test URL: www.alaskaair.com/search/hnl/bos/29nov

Video:

https://user-images.githubusercontent.com/7005799/141532539-403974d4-1213-499f-bae5-51862c2091f0.mov

**Comment by blackfalcon** [comment]
Is this not the same issue that was addressed with this update? https://github.com/AlaskaAirlines/auro-accordion/pull/33/files#diff-b18ccd15ec95e2a9c4fead5bca9085042af688361a24d3463c27138e3c797a5bR32

**Comment by aesthetiques** [comment]
Hey Dale, I found that unless the 
![image](https://user-images.githubusercontent.com/25255197/142301458-c65bda03-d1a2-4f3e-b413-8adbf001e023.png)
overflow is set to visible, it doesn't actually resolve the issue. Additionally, there are some compatibility issues with svelte and custom element properties that aren't reflected, we should probably make sure to reflect properties on our components., so that we don't have to take extra steps as a consumer. (Geoff wrote a nice article on this https://css-tricks.com/using-custom-elements-in-svelte/)
Should I go ahead and draft a PR?
