### ISSUE TITLE
auro-accordion: justifyLeft attribute no longer working

### ISSUE THREAD

**Issue by arrenkhl** [AlaskaAirlines/auro-accordion#53]
## Describe the bug
The 'justifyLeft' attribute is displaying the default chevron placement instead of moving the chevron to the left.

## To Reproduce
1. Create an auro-accordion
2. Add the justifyLeft attribute
3. Chevron does not move

## Expected behavior
The justifyLeft attribute moves the chevron left, next to the accordion text.

## Screenshots
Old accordion (correct):
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/43892293/162328555-c0516780-6c54-473e-8b6d-5a8a80a5fa96.png">

New accordion:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/43892293/162328587-adc5952b-6235-46ea-b2e1-d5c5e14fe470.png">

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Chrome
 - Version: 100.0.4896.75

## Additional context
Needed for flight search planbook dropdown

**Comment by isaiahscheel** [comment]
Is there any update on this? We may be using it wrong because it seems like others are still getting justified left like here: 

![image](https://user-images.githubusercontent.com/40191651/164279475-e6dada1e-d7db-44a5-b999-db40579bbcef.png)

Which the code is here: 
https://github.com/Alaska-ECommerce/ComponentLibrary/blob/main/components/merchandising/saver-upsell-dialog/index.ts#L126


our code is here: 
https://github.com/Alaska-ECommerce/ComponentLibrary/blob/main/components/merchandising/saver-upsell-dialog/index.ts#L126

See it live here: https://www.alaskaair.com/search/results?O=SEA&D=ALW&OD=05/18/22&OT=Anytime&RT=false&ShoppingMethod=standard
