### ISSUE TITLE
auro-accordion: accordion does not grow if components are added after the accordion is expanded

### ISSUE THREAD

**Issue by joshbenard** [AlaskaAirlines/auro-accordion#7]
## Describe the bug
The accordion does not grow when additional dom objects are added after an accordion is expanded. You are able to close and reopen the accordion to resolve the issue, but this may be annoying to an end-user.

## To Reproduce
This can be reproduced in the existing auro-accordion demo page.

1. Open an accordion on the page
2. Right-click and inspect the accordion
3. Copy some elements of the DOM that exist inside the accordion
4. Paste them back into the accordion
5. Observe that the bottom-most elements are now cutoff because the height of the expanded accordion is preset upon opening.

## Expected behavior
I would expect an accordion to grow in an expanded state as elements are added/removed.

## Screenshots
Open accordion with _only_ the elements that existed when the accordion was opened:
![image](https://user-images.githubusercontent.com/74743599/103932083-2c37a600-50d6-11eb-8491-60d1f4dd0812.png)

Open accordion after elements have been added without closing/reopening:
![image](https://user-images.githubusercontent.com/74743599/103932241-67d27000-50d6-11eb-82b4-a54382b3d35d.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141 (64-Bit)

**Comment by blackfalcon** [comment]
Thanks @joshbenard you raised an interesting issue that is not specific to the use case you offer. This issue is able to be reproduced if the page simply resized. For the accordion feature, we are leaning on the Element.scrollHeight feature that I am not finding any evidence of responsive support. 

So, saving a total redevelopment of this part of the feature, I offer that we simply add `overflow-y: auto;`

Given that a typical user will not resize a viewport and the addition/removal of content within the accordion is typical, I feel that this solution addresses your issue and corrects the user experience you speak to.

**Comment by blackfalcon** [comment]
See demo here: https://auro-accordion.surge.sh/components/auro/accordion

**Comment by joshbenard** [comment]
Yeah, that seems to work great to me! Ship it! :)
